messages:
  login-welcome: "§6Добро пожаловать на сервер! Залогиньтесь, используя \n§e/login <пароль>"
  login-no-password: "§cВы не указали пароль! Используйте \n§e/login <пароль>"
  login-succsess: "§2Успешный вход! Перенаправление в лобби через 2 секунды!"
  login-fail: "§4Неверный пароль, попробуйте снова!"
  register-welcome: "§6Добро пожаловать на сервер! Зарегистрируйтесь, используя \n§e/register <пароль> <повтор пароля>"
  register-no-password: "§cВы не указали пароли! Используйте \n§e/register <пароль> <повтор пароля>"
  register-succsess: "§2Успешная регистрация! Перенаправление в лобби через 2 секунды!"
  register-already: "§3Аккаунт уже зарегистрирован, используйте /login <пароль>, чтобы войти."
  register-error: "§cЧто-то пошло не так! Обратитесь к администрации, если считаете, что это не ваша проблема."
  register-missmatch: "§cПароли не совпадают или их вообще нет, трай эген"
  
  login-full: "§6Слишком много людей логинится одновременно, попробуй через минутку!"
  login-toolong: "§cТы слишком долго логинился!"